const MOCK_MAKERS = [
  {
    membershipId: 'mk-001',
    name: 'Harry Potter',
    purpose: 'Working on a project',
    workingOn: 'Marauder Map refresh',
    avatar: '',
  },
  {
    membershipId: 'mk-002',
    name: 'Hermione Granger',
    purpose: 'Self Learning',
    workingOn: 'Advanced arithmancy notes',
    avatar: '',
  },
  {
    membershipId: 'mk-003',
    name: 'Rubeus Hagrid',
    purpose: 'On duty',
    workingOn: 'Care of magical creatures desk',
    avatar: '',
  },
  {
    membershipId: 'mk-004',
    name: 'Luna Lovegood',
    purpose: 'Attending an event',
    workingOn: 'Spectrespecs prototyping night',
    avatar: '',
  },
  {
    membershipId: 'mk-005',
    name: 'Ron Weasley',
    purpose: 'Working on a project',
    projectName: 'Wizard chess scoreboard',
    avatar: '',
  },
  {
    membershipId: 'mk-006',
    name: 'Ginny Weasley',
    purpose: 'Visiting',
    workingOn: 'Daily Prophet open house',
    avatar: '',
  },
  {
    membershipId: 'mk-007',
    name: 'Harry Potter',
    purpose: 'Working on a project',
    workingOn: 'Marauder Map refresh',
    avatar: '',
  },
  {
    membershipId: 'mk-008',
    name: 'Hermione Granger',
    purpose: 'Self Learning',
    workingOn: 'Advanced arithmancy notes',
    avatar: '',
  },
  {
    membershipId: 'mk-009',
    name: 'Rubeus Hagrid',
    purpose: 'On duty',
    workingOn: 'Care of magical creatures desk',
    avatar: '',
  },
  {
    membershipId: 'mk-010',
    name: 'Luna Lovegood',
    purpose: 'Attending an event',
    workingOn: 'Spectrespecs prototyping night',
    avatar: '',
  },
  {
    membershipId: 'mk-011',
    name: 'Ron Weasley',
    purpose: 'Working on a project',
    projectName: 'Wizard chess scoreboard',
    avatar: '',
  },
  {
    membershipId: 'mk-012',
    name: 'Ginny Weasley',
    purpose: 'Visiting',
    workingOn: 'Daily Prophet open house',
    avatar: '',
  },
  {
    membershipId: 'mk-013',
    name: 'Harry Potter',
    purpose: 'Working on a project',
    workingOn: 'Marauder Map refresh',
    avatar: '',
  },
  {
    membershipId: 'mk-014',
    name: 'Hermione Granger',
    purpose: 'Self Learning',
    workingOn: 'Advanced arithmancy notes',
    avatar: '',
  },
  {
    membershipId: 'mk-015',
    name: 'Rubeus Hagrid',
    purpose: 'On duty',
    workingOn: 'Care of magical creatures desk',
    avatar: '',
  },
  {
    membershipId: 'mk-016',
    name: 'Luna Lovegood',
    purpose: 'Attending an event',
    workingOn: 'Spectrespecs prototyping night',
    avatar: '',
  },
  {
    membershipId: 'mk-017',
    name: 'Ron Weasley',
    purpose: 'Working on a project',
    projectName: 'Wizard chess scoreboard',
    avatar: '',
  },
  {
    membershipId: 'mk-018',
    name: 'Ginny Weasley',
    purpose: 'Visiting',
    workingOn: 'Daily Prophet open house',
    avatar: '',
  },
  {
    membershipId: 'mk-019',
    name: 'Harry Potter',
    purpose: 'Working on a project',
    workingOn: 'Marauder Map refresh',
    avatar: '',
  },
  {
    membershipId: 'mk-020',
    name: 'Hermione Granger',
    purpose: 'Self Learning',
    workingOn: 'Advanced arithmancy notes',
    avatar: '',
  },
  {
    membershipId: 'mk-021',
    name: 'Rubeus Hagrid',
    purpose: 'On duty',
    workingOn: 'Care of magical creatures desk',
    avatar: '',
  },
  {
    membershipId: 'mk-022',
    name: 'Luna Lovegood',
    purpose: 'Attending an event',
    workingOn: 'Spectrespecs prototyping night',
    avatar: '',
  },
  {
    membershipId: 'mk-023',
    name: 'Ron Weasley',
    purpose: 'Working on a project',
    projectName: 'Wizard chess scoreboard',
    avatar: '',
  },
  {
    membershipId: 'mk-024',
    name: 'Ginny Weasley',
    purpose: 'Visiting',
    workingOn: 'Daily Prophet open house',
    avatar: '',
  },
  {
    membershipId: 'mk-025',
    name: 'Harry Potter',
    purpose: 'Working on a project',
    workingOn: 'Marauder Map refresh',
    avatar: '',
  },
  {
    membershipId: 'mk-026',
    name: 'Hermione Granger',
    purpose: 'Self Learning',
    workingOn: 'Advanced arithmancy notes',
    avatar: '',
  },
  {
    membershipId: 'mk-027',
    name: 'Rubeus Hagrid',
    purpose: 'On duty',
    workingOn: 'Care of magical creatures desk',
    avatar: '',
  },
  {
    membershipId: 'mk-028',
    name: 'Luna Lovegood',
    purpose: 'Attending an event',
    workingOn: 'Spectrespecs prototyping night',
    avatar: '',
  },
  {
    membershipId: 'mk-029',
    name: 'Ron Weasley',
    purpose: 'Working on a project',
    projectName: 'Wizard chess scoreboard',
    avatar: '',
  },
  {
    membershipId: 'mk-030',
    name: 'Ginny Weasley',
    purpose: 'Visiting',
    workingOn: 'Daily Prophet open house',
    avatar: '',
  },
  {
    membershipId: 'mk-031',
    name: 'Harry Potter',
    purpose: 'Working on a project',
    workingOn: 'Marauder Map refresh',
    avatar: '',
  },
  {
    membershipId: 'mk-032',
    name: 'Hermione Granger',
    purpose: 'Self Learning',
    workingOn: 'Advanced arithmancy notes',
    avatar: '',
  },
  {
    membershipId: 'mk-033',
    name: 'Rubeus Hagrid',
    purpose: 'On duty',
    workingOn: 'Care of magical creatures desk',
    avatar: '',
  },
  {
    membershipId: 'mk-034',
    name: 'Luna Lovegood',
    purpose: 'Attending an event',
    workingOn: 'Spectrespecs prototyping night',
    avatar: '',
  },
  {
    membershipId: 'mk-035',
    name: 'Ron Weasley',
    purpose: 'Working on a project',
    projectName: 'Wizard chess scoreboard',
    avatar: '',
  },
  {
    membershipId: 'mk-036',
    name: 'Ginny Weasley',
    purpose: 'Visiting',
    workingOn: 'Daily Prophet open house',
    avatar: '',
  },
  {
    membershipId: 'mk-037',
    name: 'Harry Potter',
    purpose: 'Working on a project',
    workingOn: 'Marauder Map refresh',
    avatar: '',
  },
  {
    membershipId: 'mk-038',
    name: 'Hermione Granger',
    purpose: 'Self Learning',
    workingOn: 'Advanced arithmancy notes',
    avatar: '',
  },
  {
    membershipId: 'mk-039',
    name: 'Rubeus Hagrid',
    purpose: 'On duty',
    workingOn: 'Care of magical creatures desk',
    avatar: '',
  },
  {
    membershipId: 'mk-040',
    name: 'Luna Lovegood',
    purpose: 'Attending an event',
    workingOn: 'Spectrespecs prototyping night',
    avatar: '',
  },
  {
    membershipId: 'mk-041',
    name: 'Ron Weasley',
    purpose: 'Working on a project',
    projectName: 'Wizard chess scoreboard',
    avatar: '',
  },
  {
    membershipId: 'mk-042',
    name: 'Ginny Weasley',
    purpose: 'Visiting',
    workingOn: 'Daily Prophet open house',
    avatar: '',
  },
  {
    membershipId: 'mk-043',
    name: 'Harry Potter',
    purpose: 'Working on a project',
    workingOn: 'Marauder Map refresh',
    avatar: '',
  },
  {
    membershipId: 'mk-044',
    name: 'Hermione Granger',
    purpose: 'Self Learning',
    workingOn: 'Advanced arithmancy notes',
    avatar: '',
  },
  {
    membershipId: 'mk-045',
    name: 'Rubeus Hagrid',
    purpose: 'On duty',
    workingOn: 'Care of magical creatures desk',
    avatar: '',
  },
  {
    membershipId: 'mk-046',
    name: 'Luna Lovegood',
    purpose: 'Attending an event',
    workingOn: 'Spectrespecs prototyping night',
    avatar: '',
  },
  {
    membershipId: 'mk-047',
    name: 'Ron Weasley',
    purpose: 'Working on a project',
    projectName: 'Wizard chess scoreboard',
    avatar: '',
  },
  {
    membershipId: 'mk-048',
    name: 'Ginny Weasley',
    purpose: 'Visiting',
    workingOn: 'Daily Prophet open house',
    avatar: '',
  },
];

function getMockMakers() {
  return MOCK_MAKERS;
}

module.exports = {
  getMockMakers,
};
